### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HunBurry** [TheRealUnknownDeveloper/TruthAndDareBot-Discord-Edition#3]
Is running the bot myself the only way to get it to work?

**Comment by TheRealUnknownDeveloper** [comment]
Due to no funds to host it anywhere and while still searching for a free way to host it ATM this is the only way. If you'd like you can donate using BitCoins

**Comment by TheRealUnknownDeveloper** [comment]
1LLGFUnY2kh5n7u3vJXZn43xKpmY1dPh6c <- My wallet
