### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by dannymichel** [TheRealUnknownDeveloper/TruthAndDareBot-Discord-Edition#8]
This is bad
I fixed it myself
Doesn't work

**Comment by austinhuang0131** [comment]
the API is password-protected plus the owner shut it down

**Comment by TheRealUnknownDeveloper** [comment]
@dannymichel Hi there! The Repo is not maintained anymore so good for you :). If you want Fork it and keep a version of it cause i don't care anymore about it. Yes the API is Password protected and I'm not going to give you the password to it
